config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'items#index'
  resources :items do
    resources :purchases, only:[:create, :new]
    resources :comments, only: [:create]
  end
  
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  before_action :set_item

  def new
    if Purchase.exists?(item_id: @item.id) || @item.user.id == current_user.id
      redirect_to root_path
    else
      @purchase = AddressPurchase.new
    end
  end

  def create
    @purchase = AddressPurchase.new(purchase_params)
    if @purchase.valid?
      pay_item
      @purchase.save
      return redirect_to root_path
    else
      render :new
    end
  end

  private
  def purchase_params
    params.permit(:token, :address_id, :zipcode, :prefecture_id, :city, :address_line, :phone_number, :building).merge(user_id: current_user.id, item_id: @item.id)
  end

  def set_item
    @item = Item.find(params[:item_id])
  end

  def pay_item
    Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
    Payjp::Charge.create(
      amount: @item.price,
      card: purchase_params[:token],
      currency: 'jpy'
    )
  end

end

app/views/purchases/new.html.haml
= render "shared/second-header"
.transaction-contents
  .transaction-main
    %h1.transaction-title-text
      購入内容の確認
    .buy-item-info
      = image_tag @item.image, class: 'buy-item-img'
      .buy-item-right-content
        %h2.buy-item-text
          = @item.explanation
        .buy-item-price
          %p.item-price-text
            = "¥#{@item.price}"
          %p.item-price-sub-text （税込）送料込み
    .item-payment
      %h1.item-payment-title
        支払金額
      %p.item-payment-price
        = "¥#{@item.price}"
    = form_with id: 'charge-form', url: item_purchases_path(@item.id), class: 'transaction-form-wrap',local: true do |f|
      .credit-card-form
        %h1.info-input-haedline
          クレジットカード情報入力
        .form-group
          .form-text-wrap
            %label.form-text カード情報
            %span.indispensable 必須
          = f.text_field :number, class:"input-default number", placeholder:"カード番号(半角英数字)", maxlength:"16"
          .available-card
            = image_tag 'card-visa.gif', class: 'card-logo'
            = image_tag 'card-mastercard.gif', class: 'card-logo'
            = image_tag 'card-jcb.gif', class: 'card-logo'
            = image_tag 'card-amex.gif', class: 'card-logo'
        .form-group
          .form-text-wrap
            %label.form-text 有効期限
            %span.indispensable 必須
          .input-expiration-date-wrap
            = f.text_area :exp_month, class:"input-expiration-date exp_month", placeholder:"例)3"
            %p 月
            = f.text_area :exp_year, class:"input-expiration-date exp_year", placeholder:"例)23"
            %p 年
        .form-group
          .form-text-wrap
            %label.form-text セキュリティコード
            %span.indispensable 必須
          = f.text_field :cvc, class:"input-default cvc", placeholder:"カード背面4桁もしくは3桁の番号", maxlength:"4"
      .shipping-address-form
        %h1.info-input-haedline
          配送先入力
        .form-group
          .form-text-wrap
            %label.form-text 郵便番号
            %span.indispensable 必須
          = f.text_field :zipcode, class:"input-default", placeholder:"例）123-4567", maxlength:"8"
        .form-group
          .form-text-wrap
            %label.form-text 都道府県
            %span.indispensable 必須
          = f.collection_select :prefecture_id, Prefecture.all, :id, :name, {}, class:"select-box"
        .form-group
          .form-text-wrap
            %label.form-text 市区町村
            %span.indispensable 必須
          = f.text_field :city, class:"input-default", placeholder:"例）横浜市緑区"
        .form-group
          .form-text-wrap
            %label.form-text 番地
            %span.indispensable 必須
          = f.text_field :address_line, class:"input-default", placeholder:"例）青山1-1-1"
        .form-group
          .form-text-wrap
            %label.form-text 建物名
            %span.form-any 任意
          = f.text_field :building, class:"input-default", placeholder:"例）柳ビル103"
        .form-group
          .form-text-wrap
            %label.form-text 電話番号
            %span.indispensable 必須
          = f.text_field :phone_number, class:"input-default", placeholder:"例）09012345678",maxlength:"11"
      .buy-btn
        = f.submit "購入" ,class:"buy-red-btn"
= render "shared/second-footer"